# vagrant reload

# BOX_IMAGE = "boxomatic/centos-stream-9"
# BOX_IMAGE = "bento/ubuntu-20.04"
# BOX_IMAGE = "FEBO/suse12"
BOX_IMAGE = "opensuse/Tumbleweed.x86_64"
NODE_COUNT = 2

$ETC_HOSTS = <<-EOF
echo "10.0.1.100 main" >> /etc/hosts
echo "10.0.1.101 node-1" >> /etc/hosts
echo "10.0.1.102 node-2" >> /etc/hosts
EOF

$K3S_SETUP = <<-EOF
curl -sfL https://get.k3s.io | sh -
EOF

Vagrant.configure("2") do |config|
  config.vm.define "main" do |host|
    config.vm.provider "virtualbox" do |v|
      v.memory = "4096"
      v.cpus = "4"
    end 

    host.vm.box = BOX_IMAGE
    host.vm.hostname = "main"
    # host.vm.network "public_network", 
    # bridge: [ "en3: Hyper-V Virtual Ethernet Adapter #7", "en4: Hyper-V Virtual Ethernet Adapter", ]
    
    # , bridge: "eth1", auto_config: false
    #  use_dhcp_assigned_default_route: true, 
    #  bridge: "en1: Hyper-V Virtual Ethernet Adapter" 
    host.vm.network "private_network", ip: "10.0.1.100"
    host.vm.network "private_network", ip: "192.168.57.100"
 
  end

  # $ETC_HOSTS = <<-EOF
  # echo "10.0.1.100 main" >> /etc/hosts
  # echo "10.0.1.101 node-1" >> /etc/hosts
  # echo "10.0.1.102 node-2" >> /etc/hosts
  # EOF

  config.vm.provision "shell", inline: $ETC_HOSTS

  
# Vagrant.configure("2") do |config|
    config.vm.define "node-1" do |host|
      host.vm.box = BOX_IMAGE
      host.vm.hostname = "node-1"
      host.vm.network "private_network", ip: "10.0.1.101"
      host.vm.network "private_network", ip: "192.168.57.101"
      host.vm.provision "shell", inline: $K3S_SETUP
      host.vm.provision "shell", inline: "sudo chmod 604 /etc/rancher/k3s/k3s.yaml"
    end

    # config.vm.provision "shell", inline: $K3S_SETUP
  
# Vagrant.configure("2") do |config|
   config.vm.define "node-2" do |host|
      host.vm.box = BOX_IMAGE
      host.vm.hostname = "node-2"
      host.vm.network "private_network", ip: "10.0.1.102"
      host.vm.network "private_network", ip: "192.168.57.102"
      host.vm.provision "shell", inline: <<-EOF 
      echo "Hello World" >> /tmp/tf.txt
      EOF
    end
    
    
end


